/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type CompanyControllerGetCompanyTemplatesParams = { skip?: number | null; take?: number | null; ImageTemplates?: boolean | null; TextTemplates?: boolean | null; MapTemplates?: boolean | null; langCode?: string | null };
