/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface ConversationCreateV1Dto {
  /** 
    List of user ids to add to the conversation. In case of a user to user conversation, only 1 id is required (the other user id)
    In case of a group conversation, at least 2 ids are required (the other users ids).

    Note: group conversation is not related to the group feature
     */
  participants: number[];
}
