/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { GetTextTemplateRes } from './getTextTemplateRes';
import type { GetImageTemplates } from './getImageTemplates';
import type { GetMapTemplates } from './getMapTemplates';

export interface GetCompanyTemplatesRes {
  id: number;
  name: string;
  defaultLangCode: string;
  /** text template records */
  TextTemplates: GetTextTemplateRes[];
  /** image template records */
  ImageTemplates: GetImageTemplates[];
  /** map template records */
  MapTemplates: GetMapTemplates[];
}
