/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type GetStationResTemplateType = typeof GetStationResTemplateType[keyof typeof GetStationResTemplateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetStationResTemplateType = {
  Image: 'Image',
  Slideshow: 'Slideshow',
  Text: 'Text',
  Map: 'Map',
} as const;
