/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { GetStationResTemplateType } from './getStationResTemplateType';

export interface GetStationRes {
  id: number;
  stationRef: string;
  companyId: number;
  contentRefId: number;
  templateType: GetStationResTemplateType;
}
