/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetTextTemplateRes {
  id: number;
  description: string;
  langCode: string;
  title: string;
  tagId: number;
}
