/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type GetUserResLocale = typeof GetUserResLocale[keyof typeof GetUserResLocale];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserResLocale = {
  en: 'en',
  fr: 'fr',
  es: 'es',
} as const;
