/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserResLocale } from './getUserResLocale';
import type { GetUserResRole } from './getUserResRole';

export interface GetUserRes {
  id: number;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  createdAt: string;
  updatedAt: string;
  emailVerified: boolean;
  locale: GetUserResLocale;
  Role: GetUserResRole;
}
