/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type GetUserResRole = typeof GetUserResRole[keyof typeof GetUserResRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserResRole = {
  Admin: 'Admin',
  Staff: 'Staff',
  User: 'User',
} as const;
