/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetUploadFileRes {
  /** Uploaded file id, nullable for landmark uploads */
  id: number | null;
  /** Uploaded file source url */
  source: string;
}
