/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { MessageControllerV1GetMessagesOrderBy } from './messageControllerV1GetMessagesOrderBy';

export type MessageControllerV1GetMessagesParams = { take?: number | null; skip?: number | null; cursorId?: number | null; orderBy?: MessageControllerV1GetMessagesOrderBy };
