/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type MessageControllerV1GetMessagesOrderBy = typeof MessageControllerV1GetMessagesOrderBy[keyof typeof MessageControllerV1GetMessagesOrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageControllerV1GetMessagesOrderBy = {
  desc: 'desc',
  asc: 'asc',
} as const;
