/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type PatchUserReqLocale = typeof PatchUserReqLocale[keyof typeof PatchUserReqLocale];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchUserReqLocale = {
  en: 'en',
  fr: 'fr',
  es: 'es',
} as const;
