/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserReqLocale } from './patchUserReqLocale';

export interface PatchUserReq {
  email?: string | null;
  /** Required if email, cryptoWallet isn't null */
  password?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  newPassword?: string | null;
  /** Required if newPassword is not null */
  oldPassword?: string | null;
  locale?: PatchUserReqLocale;
}
