/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PostTextTemplateReq {
  description: string;
  title?: string;
  langCode: string;
  companyId: number;
  tagId?: number;
  tagLabel?: string;
}
