/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of template Image, Slideshow, Text or Map
 */
export type PostStationContentTemplateType = typeof PostStationContentTemplateType[keyof typeof PostStationContentTemplateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostStationContentTemplateType = {
  Image: 'Image',
  Slideshow: 'Slideshow',
  Text: 'Text',
  Map: 'Map',
} as const;
