/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserReqLocale } from './postUserReqLocale';

export interface PostUserReq {
  password: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  locale: PostUserReqLocale;
}
