/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PostStationContentTemplateType } from './postStationContentTemplateType';

export interface PostStationContent {
  stationRef: string | null;
  companyId: number;
  contentRefId: number;
  /** Type of template Image, Slideshow, Text or Map */
  templateType: PostStationContentTemplateType;
}
