/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface RefreshReq {
  /** The user current timezone, ex: Europe/Amsterdam */
  timezone?: string;
}
