/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type TemplateControllerGetCompanyTemplatesParams = { skip?: number | null; take?: number | null; langCode?: string; stationRef?: string; ImageTemplates?: boolean | null; TextTemplates?: boolean | null; MapTemplates?: boolean | null };
