/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadControllerUploadFileReference } from './uploadControllerUploadFileReference';

export type UploadControllerUploadFileParams = { reference: UploadControllerUploadFileReference; referenceId?: number | null; sendToEmail: boolean };
