/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadControllerUploadCvRef } from './uploadControllerUploadCvRef';

export type UploadControllerUploadCvParams = { refId?: number | null; ref: UploadControllerUploadCvRef };
