/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type UploadControllerUploadFileReference = typeof UploadControllerUploadFileReference[keyof typeof UploadControllerUploadFileReference];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UploadControllerUploadFileReference = {
  UserThumbnail: 'UserThumbnail',
  UserBanner: 'UserBanner',
  PracticeRoom: 'PracticeRoom',
  RoutineSession: 'RoutineSession',
  GroupCoverImage: 'GroupCoverImage',
  GroupThumbnail: 'GroupThumbnail',
  GroupProfile: 'GroupProfile',
  RoutineSessionVideo: 'RoutineSessionVideo',
  LeaderboardEntryVideo: 'LeaderboardEntryVideo',
  User: 'User',
} as const;
