/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { UploadControllerDeleteFileReference } from './uploadControllerDeleteFileReference';

export type UploadControllerDeleteFileParams = { reference: UploadControllerDeleteFileReference };
