/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  GetTextTemplateRes,
  HttpExceptionSchema,
  PostTextTemplateReq
} from '.././types'
import { customInstance } from '../../custom-instance'
import type { ErrorType } from '../../custom-instance'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const textTemplateControllerCreateTextTemplate = (
    postTextTemplateReq: PostTextTemplateReq,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetTextTemplateRes>(
      {url: `/api/v1/template/text`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: postTextTemplateReq
    },
      options);
    }
  


    export type TextTemplateControllerCreateTextTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof textTemplateControllerCreateTextTemplate>>>
    export type TextTemplateControllerCreateTextTemplateMutationBody = PostTextTemplateReq
    export type TextTemplateControllerCreateTextTemplateMutationError = ErrorType<HttpExceptionSchema>

    export const useTextTemplateControllerCreateTextTemplate = <TError = ErrorType<HttpExceptionSchema>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof textTemplateControllerCreateTextTemplate>>, TError,{data: PostTextTemplateReq}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof textTemplateControllerCreateTextTemplate>>, {data: PostTextTemplateReq}> = (props) => {
          const {data} = props ?? {};

          return  textTemplateControllerCreateTextTemplate(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof textTemplateControllerCreateTextTemplate>>, TError, {data: PostTextTemplateReq}, TContext>(mutationFn, mutationOptions)
    }
    export const textTemplateControllerGetTextTemplateOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<GetTextTemplateRes>(
      {url: `/api/v1/template/text/${id}`, method: 'get', signal
    },
      options);
    }
  

export const getTextTemplateControllerGetTextTemplateOneQueryKey = (id: number,) => [`/api/v1/template/text/${id}`];

    
export type TextTemplateControllerGetTextTemplateOneQueryResult = NonNullable<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateOne>>>
export type TextTemplateControllerGetTextTemplateOneQueryError = ErrorType<HttpExceptionSchema>

export const useTextTemplateControllerGetTextTemplateOne = <TData = Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateOne>>, TError = ErrorType<HttpExceptionSchema>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTextTemplateControllerGetTextTemplateOneQueryKey(id);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateOne>>> = ({ signal }) => textTemplateControllerGetTextTemplateOne(id, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateOne>>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const textTemplateControllerGetTextTemplateByTagIdAndLangCode = (
    tagId: number,
    langCode: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<GetTextTemplateRes>(
      {url: `/api/v1/template/text/${tagId}/${langCode}`, method: 'get', signal
    },
      options);
    }
  

export const getTextTemplateControllerGetTextTemplateByTagIdAndLangCodeQueryKey = (tagId: number,
    langCode: string,) => [`/api/v1/template/text/${tagId}/${langCode}`];

    
export type TextTemplateControllerGetTextTemplateByTagIdAndLangCodeQueryResult = NonNullable<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateByTagIdAndLangCode>>>
export type TextTemplateControllerGetTextTemplateByTagIdAndLangCodeQueryError = ErrorType<HttpExceptionSchema>

export const useTextTemplateControllerGetTextTemplateByTagIdAndLangCode = <TData = Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateByTagIdAndLangCode>>, TError = ErrorType<HttpExceptionSchema>>(
 tagId: number,
    langCode: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateByTagIdAndLangCode>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTextTemplateControllerGetTextTemplateByTagIdAndLangCodeQueryKey(tagId,langCode);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateByTagIdAndLangCode>>> = ({ signal }) => textTemplateControllerGetTextTemplateByTagIdAndLangCode(tagId,langCode, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof textTemplateControllerGetTextTemplateByTagIdAndLangCode>>, TError, TData>(queryKey, queryFn, {enabled: !!(tagId && langCode), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const textTemplateControllerIsTextTemplateExist = (
    tagId: number,
    langCode: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<boolean>(
      {url: `/api/v1/template/text/is-exist/${tagId}/${langCode}`, method: 'get', signal
    },
      options);
    }
  

export const getTextTemplateControllerIsTextTemplateExistQueryKey = (tagId: number,
    langCode: string,) => [`/api/v1/template/text/is-exist/${tagId}/${langCode}`];

    
export type TextTemplateControllerIsTextTemplateExistQueryResult = NonNullable<Awaited<ReturnType<typeof textTemplateControllerIsTextTemplateExist>>>
export type TextTemplateControllerIsTextTemplateExistQueryError = ErrorType<HttpExceptionSchema>

export const useTextTemplateControllerIsTextTemplateExist = <TData = Awaited<ReturnType<typeof textTemplateControllerIsTextTemplateExist>>, TError = ErrorType<HttpExceptionSchema>>(
 tagId: number,
    langCode: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof textTemplateControllerIsTextTemplateExist>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTextTemplateControllerIsTextTemplateExistQueryKey(tagId,langCode);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof textTemplateControllerIsTextTemplateExist>>> = ({ signal }) => textTemplateControllerIsTextTemplateExist(tagId,langCode, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof textTemplateControllerIsTextTemplateExist>>, TError, TData>(queryKey, queryFn, {enabled: !!(tagId && langCode), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

