/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  UseMutationOptions,
  MutationFunction
} from '@tanstack/react-query'
import type {
  GetUserRes,
  HttpExceptionSchema,
  LoginReq,
  RefreshReq
} from '.././types'
import { customInstance } from '../../custom-instance'
import type { ErrorType } from '../../custom-instance'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const authControllerLogin = (
    loginReq: LoginReq,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetUserRes>(
      {url: `/api/v1/iam/auth/signin`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: loginReq
    },
      options);
    }
  


    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginReq
    export type AuthControllerLoginMutationError = ErrorType<HttpExceptionSchema>

    export const useAuthControllerLogin = <TError = ErrorType<HttpExceptionSchema>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginReq}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, {data: LoginReq}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof authControllerLogin>>, TError, {data: LoginReq}, TContext>(mutationFn, mutationOptions)
    }
    export const authControllerLogout = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<void>(
      {url: `/api/v1/iam/auth/signout`, method: 'post'
    },
      options);
    }
  


    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
    
    export type AuthControllerLogoutMutationError = ErrorType<HttpExceptionSchema>

    export const useAuthControllerLogout = <TError = ErrorType<HttpExceptionSchema>,
    TVariables = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,TVariables, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, TVariables> = () => {
          

          return  authControllerLogout(requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof authControllerLogout>>, TError, TVariables, TContext>(mutationFn, mutationOptions)
    }
    export const authControllerSignAccessToken = (
    refreshReq: RefreshReq,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetUserRes>(
      {url: `/api/v1/iam/auth/refresh`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: refreshReq
    },
      options);
    }
  


    export type AuthControllerSignAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSignAccessToken>>>
    export type AuthControllerSignAccessTokenMutationBody = RefreshReq
    export type AuthControllerSignAccessTokenMutationError = ErrorType<HttpExceptionSchema>

    export const useAuthControllerSignAccessToken = <TError = ErrorType<HttpExceptionSchema>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignAccessToken>>, TError,{data: RefreshReq}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSignAccessToken>>, {data: RefreshReq}> = (props) => {
          const {data} = props ?? {};

          return  authControllerSignAccessToken(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof authControllerSignAccessToken>>, TError, {data: RefreshReq}, TContext>(mutationFn, mutationOptions)
    }
    