/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type ChatType = typeof ChatType[keyof typeof ChatType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatType = {
  Text: 'Text',
  Image: 'Image',
  Video: 'Video',
  Slideshow: 'Slideshow',
  Map: 'Map',
  Website: 'Website',
  Form: 'Form',
} as const;
