/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { ChatType } from './chatType';

export interface ContentRes {
  content?: string | null;
  contents: string[];
  extraContent?: string | null;
  id: number;
  langCode: string;
  sourceId: number;
  type: ChatType;
}
