/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { ContentControllerFindOneRefType } from './contentControllerFindOneRefType';

export type ContentControllerFindOneParams = {
sourceId: number;
refType: ContentControllerFindOneRefType;
langCode?: string;
};
