/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { ChatType } from './chatType';

export interface ContentRes {
  /** @nullable */
  content?: string | null;
  contents: string[];
  /** @nullable */
  extraContent?: string | null;
  id: number;
  langCode: string;
  sourceId: number;
  type: ChatType;
}
