/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type ContentControllerFindOneRefType = typeof ContentControllerFindOneRefType[keyof typeof ContentControllerFindOneRefType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContentControllerFindOneRefType = {
  Text: 'Text',
  Image: 'Image',
  Video: 'Video',
  Slideshow: 'Slideshow',
  Map: 'Map',
  Website: 'Website',
  Form: 'Form',
} as const;
