/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetCompanyRes {
  defaultLangCode: string;
  displayEnabled: boolean;
  id: number;
  isTrialAccount: boolean;
  isTrialActive: boolean;
  isTrialExpired: boolean;
  logoUrl: string;
  formsEnabled: boolean;
  name: string;
  recordingsEnabled: boolean;
  screensEnabled: boolean;
  stationCount: number;
  teamEnabled: boolean;
  trialDaysLeft: number | null;
  trialEndsAt: string | null;
  trialStartedAt: string | null;
  upsellEnabled: boolean;
  whatsappEnabled: boolean;
}
