/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentTemplate = {
  id: number;
  url: string;
  tag: string;
  langCode: string;
  templateId: number;
  ext: string;
  order: number;
};

export type GetDocumentTemplateRes = DocumentTemplate;

// Alternative: If you expect a single document instead of an array
export type GetSingleDocumentTemplateRes = DocumentTemplate;