/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetSurveyAnswerTemplateRes {
  createdAt: string;
  id: number;
  stationNo: number | null;
  tag: string | null;
  updatedAt: string;
  value: number | null;
}
