/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetSurveyAnswerTemplateRes {
  createdAt: string;
  id: number;
  /** @nullable */
  stationNo: number | null;
  /** @nullable */
  tag: string | null;
  updatedAt: string;
  /** @nullable */
  value: number | null;
}
