/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetSlideshowTemplateRes {
  id: number;
  langCode: string[];
  tag: string;
  templateId: number;
  url: string[];
}
