/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { GetShortcutResType } from './getShortcutResType';

export interface GetShortcutRes {
  /** @nullable */
  extraValue?: string | null;
  id: number;
  key: string;
  /** @nullable */
  order?: number | null;
  type: GetShortcutResType;
  value: string;
}
