/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetSurveyTemplateRes {
  createdAt: string;
  id: number;
  tag: string;
  templateId: number;
  updatedAt: string;
}
