/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type GetShortcutResType = typeof GetShortcutResType[keyof typeof GetShortcutResType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetShortcutResType = {
  Template: 'Template',
  Language: 'Language',
  DefaultSlideshow: 'DefaultSlideshow',
} as const;
