/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface GetTextTemplateRes {
  content: string;
  id: number;
  langCode: string[];
  tag: string;
  templateId: number;
}
