/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserResBackendTokens } from './getUserResBackendTokens';
import type { GetUserResRolesItem } from './getUserResRolesItem';

export interface GetUserRes {
  backendTokens: GetUserResBackendTokens;
  companyId: number | null;
  createdAt: string;
  email: string | null;
  emailVerified: boolean;
  firstName: string | null;
  id: number;
  isTrialAccount: boolean;
  isTrialActive: boolean;
  isTrialExpired: boolean;
  lastName: string | null;
  Roles: GetUserResRolesItem[] | null;
  trialDaysLeft: number | null;
  trialEndsAt: string | null;
  trialStartedAt: string | null;
  updatedAt: string;
}

export interface GetUserListRes {
  id: number;
  email: string | null;
  Roles: string[] | null;
}
