/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserResBackendTokens } from './getUserResBackendTokens';
import type { GetUserResRolesItem } from './getUserResRolesItem';

export interface GetUserRes {
  backendTokens: GetUserResBackendTokens;
  companyId: number;
  createdAt: string;
  /** @nullable */
  email: string | null;
  emailVerified: boolean;
  /** @nullable */
  firstName: string | null;
  id: number;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  Roles: GetUserResRolesItem[] | null;
  updatedAt: string;
}
