/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type GetUserResRolesItem = typeof GetUserResRolesItem[keyof typeof GetUserResRolesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserResRolesItem = {
  Admin: 'Admin',
  Staff: 'Staff',
  User: 'User',
} as const;
