/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PatchMapTemplateReq {
  defaultLangCode: string;
  destination?: string | null;
  langCode?: string | null;
  origin?: string | null;
}
