/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchFormTemplateReqValues } from './patchFormTemplateReqValues';

export interface PatchFormTemplateReq {
  defaultLangCode: string;
  langCode?: string | null;
  values: PatchFormTemplateReqValues;
}
