/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PatchTextTemplateReq {
  /** @nullable */
  content?: string | null;
  /** */
  defaultLangCode: string;
  /** @nullable */
  langCode?: string | null;
}
