/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserReqRoles } from './patchUserReqRoles';

export interface PatchUserReq {
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  newPassword?: string | null;
  /** Required if newPassword is not null */
  oldPassword?: string | null;
  /** Required if email, cryptoWallet isn't null */
  password?: string | null;
  Roles?: PatchUserReqRoles;
}
