/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PatchUserReqRoles } from './patchUserReqRoles';

export interface PatchUserReq {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  newPassword?: string | null;
  /**
   * Required if newPassword is not null
   * @nullable
   */
  oldPassword?: string | null;
  /**
   * Required if email, cryptoWallet isn't null
   * @nullable
   */
  password?: string | null;
  /** @nullable */
  Roles?: PatchUserReqRoles;
}
