/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PatchMapTemplateReq {
  /** */
  defaultLangCode: string;
  /** @nullable */
  destination?: string | null;
  /** @nullable */
  langCode?: string | null;
  /** @nullable */
  origin?: string | null;
}
