/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type PatchUserReqRoles = typeof PatchUserReqRoles[keyof typeof PatchUserReqRoles] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchUserReqRoles = {
  Admin: 'Admin',
  Staff: 'Staff',
  User: 'User',
} as const;
