/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PatchSlideshowTemplateReq {
  /** @nullable */
  defaultLangCode?: string | null;
  /** @nullable */
  langCode?: string | null;
  /** @nullable */
  urls?: string[] | null;
}
