/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

/**
 */
export type PostShortcutReqType = typeof PostShortcutReqType[keyof typeof PostShortcutReqType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostShortcutReqType = {
  Template: 'Template',
  Language: 'Language',
  DefaultSlideshow: 'DefaultSlideshow',
} as const;
