/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type PostUserReqRoles = typeof PostUserReqRoles[keyof typeof PostUserReqRoles] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserReqRoles = {
  Admin: 'Admin',
  Staff: 'Staff',
  User: 'User',
} as const;
