/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserReqRoles } from './postUserReqRoles';

export interface PostUserReq {
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  password: string;
  Roles?: PostUserReqRoles;
}
