/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PostShortcutReq } from './postShortcutReq';

export interface PostShortcutManyReq {
  postShortCutReqArray: PostShortcutReq[];
}
