/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PostCompanyReq {
  /** @nullable */
  defaultLangCode?: string | null;
  /** @nullable */
  logoUrl?: string | null;
  /** */
  name: string;
  /** */
  stationCount: number;
}
