/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PostUserReqRoles } from './postUserReqRoles';

export interface PostUserReq {
  email: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  password: string;
  /** @nullable */
  Roles?: PostUserReqRoles;
}
