/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export interface PostCompanyReq {
  defaultLangCode?: string | null;
  displayEnabled?: boolean | null;
  formsEnabled?: boolean | null;
  logoUrl?: string | null;
  name: string;
  recordingsEnabled?: boolean | null;
  screensEnabled?: boolean | null;
  stationCount: number;
  teamEnabled?: boolean | null;
  upsellEnabled?: boolean | null;
  whatsappEnabled?: boolean | null;
}
