/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { PostShortcutReqType } from './postShortcutReqType';

export interface PostShortcutReq {
  /** @nullable */
  extraValue?: string | null;
  /** @nullable */
  key?: string | null;
  /** */
  order?: number;
  /** */
  type: PostShortcutReqType;
  /** */
  value: string;
}
