/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type ShortcutControllerGetShortcutManyType = typeof ShortcutControllerGetShortcutManyType[keyof typeof ShortcutControllerGetShortcutManyType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShortcutControllerGetShortcutManyType = {
  Template: 'Template',
  Language: 'Language',
  DefaultSlideshow: 'DefaultSlideshow',
} as const;
