/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type ShortcutControllerGetShortcutOneType = typeof ShortcutControllerGetShortcutOneType[keyof typeof ShortcutControllerGetShortcutOneType] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShortcutControllerGetShortcutOneType = {
  Template: 'Template',
  Language: 'Language',
  DefaultSlideshow: 'DefaultSlideshow',
} as const;
