/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import type { ShortcutControllerGetShortcutManyType } from './shortcutControllerGetShortcutManyType';

export type ShortcutControllerGetShortcutManyParams = {
key?: string | null;
value?: string | null;
type?: ShortcutControllerGetShortcutManyType;
};
