/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type UploadControllerUploadCompanyFileManyBody = {
  defaultLangCode: string;
  file: Blob[];
  itemsMetadata?: string;
  langCode: string;
  tag: string;
};
