/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type UploadControllerUploadCompanyFileBody = {
  defaultLangCode: string;
  file: Blob;
  langCode: string;
  tag: string;
};
