/**
 * Generated by orval v6.26.0 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */

export type UserControllerGetUsersParams = {
/**
 * Paginate
 */
skip?: number | null;
/**
 * Paginate
 */
take?: number | null;
/**
 * search for user email
 */
email?: string | null;
};
