/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  GetCompanyRes,
  HttpExceptionSchema,
  PostCompanyReq,
  GetCompanyTemplatesRes,
  CompanyControllerGetCompanyTemplatesParams
} from '.././types'
import { customInstance } from '../../custom-instance'
import type { ErrorType } from '../../custom-instance'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const companyControllerCreateCompany = (
    postCompanyReq: PostCompanyReq,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetCompanyRes>(
      {url: `/api/v1/company`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: postCompanyReq
    },
      options);
    }
  


    export type CompanyControllerCreateCompanyMutationResult = NonNullable<Awaited<ReturnType<typeof companyControllerCreateCompany>>>
    export type CompanyControllerCreateCompanyMutationBody = PostCompanyReq
    export type CompanyControllerCreateCompanyMutationError = ErrorType<HttpExceptionSchema>

    export const useCompanyControllerCreateCompany = <TError = ErrorType<HttpExceptionSchema>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof companyControllerCreateCompany>>, TError,{data: PostCompanyReq}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof companyControllerCreateCompany>>, {data: PostCompanyReq}> = (props) => {
          const {data} = props ?? {};

          return  companyControllerCreateCompany(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof companyControllerCreateCompany>>, TError, {data: PostCompanyReq}, TContext>(mutationFn, mutationOptions)
    }
    export const companyControllerGetUserCompany = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<GetCompanyRes>(
      {url: `/api/v1/company`, method: 'get', signal
    },
      options);
    }
  

export const getCompanyControllerGetUserCompanyQueryKey = () => [`/api/v1/company`];

    
export type CompanyControllerGetUserCompanyQueryResult = NonNullable<Awaited<ReturnType<typeof companyControllerGetUserCompany>>>
export type CompanyControllerGetUserCompanyQueryError = ErrorType<HttpExceptionSchema>

export const useCompanyControllerGetUserCompany = <TData = Awaited<ReturnType<typeof companyControllerGetUserCompany>>, TError = ErrorType<HttpExceptionSchema>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof companyControllerGetUserCompany>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompanyControllerGetUserCompanyQueryKey();

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof companyControllerGetUserCompany>>> = ({ signal }) => companyControllerGetUserCompany(requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof companyControllerGetUserCompany>>, TError, TData>(queryKey, queryFn, queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const companyControllerGetCompanyOne = (
    companyId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<GetCompanyRes>(
      {url: `/api/v1/company/${companyId}`, method: 'get', signal
    },
      options);
    }
  

export const getCompanyControllerGetCompanyOneQueryKey = (companyId: number,) => [`/api/v1/company/${companyId}`];

    
export type CompanyControllerGetCompanyOneQueryResult = NonNullable<Awaited<ReturnType<typeof companyControllerGetCompanyOne>>>
export type CompanyControllerGetCompanyOneQueryError = ErrorType<HttpExceptionSchema>

export const useCompanyControllerGetCompanyOne = <TData = Awaited<ReturnType<typeof companyControllerGetCompanyOne>>, TError = ErrorType<HttpExceptionSchema>>(
 companyId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof companyControllerGetCompanyOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompanyControllerGetCompanyOneQueryKey(companyId);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof companyControllerGetCompanyOne>>> = ({ signal }) => companyControllerGetCompanyOne(companyId, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof companyControllerGetCompanyOne>>, TError, TData>(queryKey, queryFn, {enabled: !!(companyId), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const companyControllerGetCompanyTemplates = (
    companyId: number,
    params?: CompanyControllerGetCompanyTemplatesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<GetCompanyTemplatesRes>(
      {url: `/api/v1/company/${companyId}/templates`, method: 'get',
        params, signal
    },
      options);
    }
  

export const getCompanyControllerGetCompanyTemplatesQueryKey = (companyId: number,
    params?: CompanyControllerGetCompanyTemplatesParams,) => [`/api/v1/company/${companyId}/templates`, ...(params ? [params]: [])];

    
export type CompanyControllerGetCompanyTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof companyControllerGetCompanyTemplates>>>
export type CompanyControllerGetCompanyTemplatesQueryError = ErrorType<HttpExceptionSchema>

export const useCompanyControllerGetCompanyTemplates = <TData = Awaited<ReturnType<typeof companyControllerGetCompanyTemplates>>, TError = ErrorType<HttpExceptionSchema>>(
 companyId: number,
    params?: CompanyControllerGetCompanyTemplatesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof companyControllerGetCompanyTemplates>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCompanyControllerGetCompanyTemplatesQueryKey(companyId,params);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof companyControllerGetCompanyTemplates>>> = ({ signal }) => companyControllerGetCompanyTemplates(companyId,params, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof companyControllerGetCompanyTemplates>>, TError, TData>(queryKey, queryFn, {enabled: !!(companyId), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

