/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  UseMutationOptions,
  MutationFunction
} from '@tanstack/react-query'
import type {
  GetStationRes,
  HttpExceptionSchema,
  PostStationContent
} from '.././types'
import { customInstance } from '../../custom-instance'
import type { ErrorType } from '../../custom-instance'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const stationControllerPostStationContent = (
    postStationContent: PostStationContent,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetStationRes[]>(
      {url: `/api/v1/station`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: postStationContent
    },
      options);
    }
  


    export type StationControllerPostStationContentMutationResult = NonNullable<Awaited<ReturnType<typeof stationControllerPostStationContent>>>
    export type StationControllerPostStationContentMutationBody = PostStationContent
    export type StationControllerPostStationContentMutationError = ErrorType<HttpExceptionSchema>

    export const useStationControllerPostStationContent = <TError = ErrorType<HttpExceptionSchema>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationControllerPostStationContent>>, TError,{data: PostStationContent}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stationControllerPostStationContent>>, {data: PostStationContent}> = (props) => {
          const {data} = props ?? {};

          return  stationControllerPostStationContent(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof stationControllerPostStationContent>>, TError, {data: PostStationContent}, TContext>(mutationFn, mutationOptions)
    }
    