/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * Nobstacle API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useMutation
} from '@tanstack/react-query'
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey
} from '@tanstack/react-query'
import type {
  GetTagRes,
  HttpExceptionSchema,
  PostTagTemplate
} from '.././types'
import { customInstance } from '../../custom-instance'
import type { ErrorType } from '../../custom-instance'

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


// eslint-disable-next-line
  type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

export const tagControllerCreateTag = (
    postTagTemplate: PostTagTemplate,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetTagRes>(
      {url: `/api/v1/tag/tag`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: postTagTemplate
    },
      options);
    }
  


    export type TagControllerCreateTagMutationResult = NonNullable<Awaited<ReturnType<typeof tagControllerCreateTag>>>
    export type TagControllerCreateTagMutationBody = PostTagTemplate
    export type TagControllerCreateTagMutationError = ErrorType<HttpExceptionSchema>

    export const useTagControllerCreateTag = <TError = ErrorType<HttpExceptionSchema>,
    
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tagControllerCreateTag>>, TError,{data: PostTagTemplate}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
      const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tagControllerCreateTag>>, {data: PostTagTemplate}> = (props) => {
          const {data} = props ?? {};

          return  tagControllerCreateTag(data,requestOptions)
        }

      return useMutation<Awaited<ReturnType<typeof tagControllerCreateTag>>, TError, {data: PostTagTemplate}, TContext>(mutationFn, mutationOptions)
    }
    export const tagControllerGetTagOne = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<GetTagRes>(
      {url: `/api/v1/tag/tag/${id}`, method: 'get', signal
    },
      options);
    }
  

export const getTagControllerGetTagOneQueryKey = (id: number,) => [`/api/v1/tag/tag/${id}`];

    
export type TagControllerGetTagOneQueryResult = NonNullable<Awaited<ReturnType<typeof tagControllerGetTagOne>>>
export type TagControllerGetTagOneQueryError = ErrorType<HttpExceptionSchema>

export const useTagControllerGetTagOne = <TData = Awaited<ReturnType<typeof tagControllerGetTagOne>>, TError = ErrorType<HttpExceptionSchema>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof tagControllerGetTagOne>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTagControllerGetTagOneQueryKey(id);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tagControllerGetTagOne>>> = ({ signal }) => tagControllerGetTagOne(id, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof tagControllerGetTagOne>>, TError, TData>(queryKey, queryFn, {enabled: !!(id), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

export const tagControllerGetCompanyTags = (
    companyId: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      return customInstance<void>(
      {url: `/api/v1/tag/tag/company/${companyId}`, method: 'get', signal
    },
      options);
    }
  

export const getTagControllerGetCompanyTagsQueryKey = (companyId: number,) => [`/api/v1/tag/tag/company/${companyId}`];

    
export type TagControllerGetCompanyTagsQueryResult = NonNullable<Awaited<ReturnType<typeof tagControllerGetCompanyTags>>>
export type TagControllerGetCompanyTagsQueryError = ErrorType<HttpExceptionSchema>

export const useTagControllerGetCompanyTags = <TData = Awaited<ReturnType<typeof tagControllerGetCompanyTags>>, TError = ErrorType<HttpExceptionSchema>>(
 companyId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof tagControllerGetCompanyTags>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } => {

  const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTagControllerGetCompanyTagsQueryKey(companyId);

  

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tagControllerGetCompanyTags>>> = ({ signal }) => tagControllerGetCompanyTags(companyId, requestOptions, signal);

  const query = useQuery<Awaited<ReturnType<typeof tagControllerGetCompanyTags>>, TError, TData>(queryKey, queryFn, {enabled: !!(companyId), ...queryOptions}) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryKey;

  return query;
}

